from __future__ import annotations

import pandas as pd


REGISTRY = [
    {"column": "lap_var", "availability": "pre", "controller_allowed": True, "description": "Laplacian variance image sharpness"},
    {"column": "gray_entropy", "availability": "pre", "controller_allowed": True, "description": "Grayscale Shannon entropy"},
    {"column": "color_entropy", "availability": "pre", "controller_allowed": True, "description": "HSV color entropy"},
    {"column": "tenengrad", "availability": "pre", "controller_allowed": True, "description": "Sobel gradient energy"},
    {"column": "brenner", "availability": "pre", "controller_allowed": True, "description": "Brenner gradient focus proxy"},
    {"column": "edge_density", "availability": "pre", "controller_allowed": True, "description": "Fraction of edge pixels"},
    {"column": "local_contrast", "availability": "pre", "controller_allowed": True, "description": "Mean local absolute luminance deviation"},
    {"column": "mean_luma", "availability": "pre", "controller_allowed": True, "description": "Global mean grayscale intensity"},
    {"column": "std_luma", "availability": "pre", "controller_allowed": True, "description": "Global grayscale standard deviation"},
    {"column": "rms_contrast", "availability": "pre", "controller_allowed": True, "description": "RMS contrast proxy"},
    {"column": "n_det_count", "availability": "post_n", "controller_allowed": True, "description": "YOLOv8n detection count"},
    {"column": "n_mean_conf", "availability": "post_n", "controller_allowed": True, "description": "YOLOv8n mean confidence"},
    {"column": "n_max_conf", "availability": "post_n", "controller_allowed": True, "description": "YOLOv8n max confidence"},
    {"column": "n_conf_std", "availability": "post_n", "controller_allowed": True, "description": "YOLOv8n confidence std"},
    {"column": "n_total_area_norm", "availability": "post_n", "controller_allowed": True, "description": "YOLOv8n normalized total detection area"},
    {"column": "n_zero_det_flag", "availability": "post_n", "controller_allowed": True, "description": "YOLOv8n zero-detection flag"},
    {"column": "lap_var_delta_1", "availability": "pre", "controller_allowed": True, "description": "First-order Laplacian delta"},
    {"column": "gray_entropy_delta_1", "availability": "pre", "controller_allowed": True, "description": "First-order entropy delta"},
    {"column": "n_mean_conf_delta_1", "availability": "post_n", "controller_allowed": True, "description": "First-order confidence delta"},
    {"column": "n_det_count_delta_1", "availability": "post_n", "controller_allowed": True, "description": "First-order detection count delta"},
    {"column": "n_mean_conf_ema_fast", "availability": "post_n", "controller_allowed": True, "description": "Fast EMA on YOLOv8n mean confidence"},
    {"column": "n_mean_conf_ema_slow", "availability": "post_n", "controller_allowed": True, "description": "Slow EMA on YOLOv8n mean confidence"},
    {"column": "conf_drop", "availability": "post_n", "controller_allowed": True, "description": "Relative drop between slow and fast confidence EMAs"},
    {"column": "zero_det_streak", "availability": "post_n", "controller_allowed": True, "description": "Consecutive zero-detection frames from YOLOv8n"},
    {"column": "roi_best_conf", "availability": "post_n", "controller_allowed": True, "description": "Confidence of highest-confidence n ROI"},
    {"column": "roi_best_area_norm", "availability": "post_n", "controller_allowed": True, "description": "Area of highest-confidence n ROI"},
    {"column": "roi_lap_var", "availability": "post_n", "controller_allowed": True, "description": "ROI Laplacian variance"},
    {"column": "roi_gray_entropy", "availability": "post_n", "controller_allowed": True, "description": "ROI grayscale entropy"},
    {"column": "matched_count", "availability": "offline_only", "controller_allowed": False, "description": "Number of matched n/s detections per frame"},
    {"column": "matched_fraction_s", "availability": "offline_only", "controller_allowed": False, "description": "Fraction of s detections matched by n"},
    {"column": "mean_iou", "availability": "offline_only", "controller_allowed": False, "description": "Mean IoU across matched n/s detections"},
    {"column": "iou_disagreement", "availability": "offline_only", "controller_allowed": False, "description": "One minus mean matched IoU"},
    {"column": "det_count_gap", "availability": "offline_only", "controller_allowed": False, "description": "s minus n detection count gap"},
    {"column": "extra_dets_s_norm", "availability": "offline_only", "controller_allowed": False, "description": "Extra s detections normalized by s count"},
    {"column": "n_infer_ms", "availability": "offline_only", "controller_allowed": False, "description": "Offline YOLOv8n inference time summary"},
    {"column": "s_infer_ms", "availability": "offline_only", "controller_allowed": False, "description": "Offline YOLOv8s inference time summary"},
    {"column": "n_det_count_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference n detection count used during target construction"},
    {"column": "n_mean_conf_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference n mean confidence used during target construction"},
    {"column": "n_max_conf_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference n max confidence used during target construction"},
    {"column": "n_conf_std_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference n confidence std used during target construction"},
    {"column": "n_total_area_norm_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference n total area used during target construction"},
    {"column": "n_zero_det_flag_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference n zero-detection flag used during target construction"},
    {"column": "s_det_count_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference s detection count used during target construction"},
    {"column": "s_mean_conf_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference s mean confidence used during target construction"},
    {"column": "s_max_conf_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference s max confidence used during target construction"},
    {"column": "s_conf_std_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference s confidence std used during target construction"},
    {"column": "s_total_area_norm_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference s total area used during target construction"},
    {"column": "s_zero_det_flag_ref", "availability": "offline_only", "controller_allowed": False, "description": "Reference s zero-detection flag used during target construction"},
    {"column": "n_det_count_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline n outcome detection count"},
    {"column": "n_mean_conf_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline n outcome mean confidence"},
    {"column": "n_max_conf_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline n outcome max confidence"},
    {"column": "n_conf_std_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline n outcome confidence std"},
    {"column": "n_total_area_norm_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline n outcome total detection area"},
    {"column": "n_zero_det_flag_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline n outcome zero-detection flag"},
    {"column": "s_det_count_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline s outcome detection count"},
    {"column": "s_mean_conf_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline s outcome mean confidence"},
    {"column": "s_max_conf_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline s outcome max confidence"},
    {"column": "s_conf_std_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline s outcome confidence std"},
    {"column": "s_total_area_norm_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline s outcome total detection area"},
    {"column": "s_zero_det_flag_outcome", "availability": "offline_only", "controller_allowed": False, "description": "Offline s outcome zero-detection flag"},
    {"column": "extra_dets_s", "availability": "offline_only", "controller_allowed": False, "description": "Detections only YOLOv8s finds"},
    {"column": "extra_dets_n", "availability": "offline_only", "controller_allowed": False, "description": "Detections only YOLOv8n finds"},
    {"column": "delta_quality", "availability": "offline_only", "controller_allowed": False, "description": "Weighted offline quality delta proxy"},
    {"column": "benefit_score", "availability": "offline_only", "controller_allowed": False, "description": "Weighted offline benefit score"},
    {"column": "latency_penalty", "availability": "offline_only", "controller_allowed": False, "description": "Offline latency penalty from delta inference time"},
    {"column": "delta_infer_ms", "availability": "offline_only", "controller_allowed": False, "description": "s minus n inference time"},
    {"column": "y_hard_binary", "availability": "offline_only", "controller_allowed": False, "description": "Binary hard-frame label"},
    {"column": "y_benefit_count", "availability": "offline_only", "controller_allowed": False, "description": "Count-based benefit target"},
    {"column": "y_benefit_conf", "availability": "offline_only", "controller_allowed": False, "description": "Confidence-gap benefit target"},
    {"column": "y_benefit_iou", "availability": "offline_only", "controller_allowed": False, "description": "IoU-disagreement benefit target"},
    {"column": "y_disagreement_continuous", "availability": "offline_only", "controller_allowed": False, "description": "Continuous disagreement target"},
    {"column": "y_switch_optimal", "availability": "offline_only", "controller_allowed": False, "description": "Offline switch-optimal label"},
]


def registry_df() -> pd.DataFrame:
    return pd.DataFrame(REGISTRY)


def controller_allowed_columns() -> list[str]:
    return [row["column"] for row in REGISTRY if row["controller_allowed"]]
